apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: sample-service
  description: The Sample Service API allows you to send errors to Rollbar or Sentry.
  tags:
    - unstable
spec:
  type: openapi
  lifecycle: production
  owner: engineering
  definition:
    $text: https://github.com/RoadieHQ/sample-service/blob/main/api-spec.yaml
