---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-spotify-test-1
  description: The whole spotify api
  annotations:
    openapi/ref-basepath: ./
spec:
  type: openapi
  lifecycle: experimental
  owner: sblausten
  definition:
    $openapi: ./api-spotify-definition.yaml