apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: |
    A service for testing Backstage functionality. For example, we can trigger errors
    on the sample-service, these are sent to Sentry, then we can view them in the 
    Backstage plugin for Sentry.
  annotations:
    circleci.com/project-slug: RoadieHQ/sample-service
    github.com/project-slug: RoadieHQ/sample-service
    backstage.io/github-actions-id: RoadieHQ/sample-service
    sentry.io/project-slug: sample-service
spec:
  type: service
  owner: david@roadie.io
  lifecycle: experimental
