apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: links-test-1
  annotations:
    github.com/project-slug: sblausten/sample-service
  links:
    - url: https://www.google.com
      title: Google
spec:
  type: service
  owner: sblausten
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: links-test-2
  annotations:
    github.com/project-slug: sblausten/sample-service
  links:
    - url: https://www.google.com
      title: Google
      icon: help
    - url: https://www.graphana.com
      title: Grafana
    - url: https://www.notion.so/roadie/Sample-Service-e067465e56a14ae9b0507f8559f6aa26
      title: Datadog
      icon: dashboard
spec:
  type: service
  owner: sblausten
  lifecycle: experimental