apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: conflict-test-1
  title: Conflict test API 2 updated
  annotations:
    github.com/project-slug: sblausten/sample-service
  tags:
    - test1
spec:
  type: openapi
  owner: sblausten
  lifecycle: experimental
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: conflict-test-component-2
  title: Conflict test component 2
  annotations:
    github.com/project-slug: sblausten/sample-service
spec:
  type: service
  owner: sblausten
  lifecycle: experimental