apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-validator
  title: CodeCov Test service
  description: |
    A service for testing Backstage functionality.
  annotations:
    bugsnag.com/project-key: RoadieHQ/93b71ec25fd3e1d803af87d57cea2acd
    bugsnag.com/project-name: Test bugsnag app
    shortcut.com/project-id: '14'
    github.com/public-repository: Public
    github.com/project-slug: roadiehq/sample-service
    backstage.io/code-coverage: enabled
relations:
  - type: ownedBy
    targetRef: group:actblue/ats
spec:
  type: service
  owner: irma
  lifecycle: experimental
  system: sample-system
  providesApis:
    - test-service
