---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  annotations:
    github.com/project-slug: RoadieHQ/sample-service
    backstage.io/kubernetes-label-selector: 'app=backstage,component=frontend'
    backstage.io/techdocs-ref: dir:.
    snyk.io/org-name: roadie
    snyk.io/project-ids: 63ac09c4-fd65-4f53-b9b2-c31d2dee3291
    dev.azure.com/project-repo: roadie-test/test1
    dev.azure.com/project: roadie-test
    dev.azure.com/build-definition: sblausten.sample-service
spec:
  type: other
  lifecycle: unknown
  owner: 'user:iain@roadie.io'
