apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-2
  description: |
    A service for testing Backstage functionality. Configured for Circle CI
    and Rollbar.
  annotations:
    circleci.com/project-slug: github/RoadieHQ/sample-service
    rollbar.com/project-slug: roadie/sample-project
    aws.com/lambda-function-name: roadie-test-load-to-elastic
    aws.com/lambda-region: eu-west-1
    backstage.io/techdocs-ref: url:https://github.com/RoadieHQ/sample-service/tree/main/sub-dir-documentation
    github.com/project-slug: RoadieHQ/sample-service
    bugsnag.com/project-key: RoadieHQ/93b71ec25fd3e1d803af87d57cea2acd

spec:
  type: library
  owner: User:dtuite
  lifecycle: incorrectvalue
  system: sample-system
  providesApis:
    - sample-service
  consumesApis:
    - spotify
  dependencyOf:
    - Component:sample-service-1
