apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: conflict-test-component-new-1
  title: Component 1 conflicting
  annotations:
    github.com/project-slug: sblausten/sample-service
spec:
  type: service
  owner: sblausten
  lifecycle: experimental