---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service
  description: A test service
  annotations:
    github.com/project-slug: RoadieHQ/sample-service
    backstage.io/kubernetes-label-selector: 'app=backstage,component=frontend'
    backstage.io/techdocs-ref: dir:.
    snyk.io/org-name: roadie
    snyk.io/project-ids: 63ac09c4-fd65-4f53-b9b2-c31d2dee3291
spec:
  type: other
  lifecycle: experimental
  owner: group:engineering
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: test-moving-location
spec:
  type: url
  targets:
    - ./moving-entity.yaml
