apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-1
  description: |
    A service for testing Backstage functionality. Configured for GitHub Actions and
    Sentry.
  annotations:
    github.com/project-slug: roadiehq/sample-service
    # The Sentry organization is stored in the app-config.yaml of the Backstage instance.
    sentry.io/project-slug: sample-service
    backstage.io/techdocs-ref: dir:./
spec:
  type: service
  owner: david@roadie.io
  lifecycle: experimental
