apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-techdocs-test-techdocs-entity
  description: A service for testing TechDocs.
  annotations:
    backstage.io/techdocs-entity: component:default/sample-service-techdocs-test
spec:
  type: service
  owner: guest
  lifecycle: experimental
