apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-2
  title: Sample Service 2
  description: |
    A service for testing Backstage functionality. Configured for Circle CI
    and Rollbar.
  annotations:
    circleci.com/project-slug: github/RoadieHQ/sample-service
    rollbar.com/project-slug: RoadieHQ/sample-project
    backstage.io/techdocs-ref: url:https://github.com/RoadieHQ/sample-service/tree/main/sub-dir-documentation
    github.com/project-slug: RoadieHQ/sample-service
    bugsnag.com/project-key: roadie/404e5af6a76f748f890076e7455ee46c
spec:
  type: service
  owner: dtuite
  lifecycle: experimental
  system: sample-system
  providesApis:
    - sample-service
  consumesApis:
    - spotify
  dependencyOf:
    - Component:sample-service-1
  partOf:
    - Domain:demos
