apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-service
  title: Test service
  description: |
    A service for testing Backstage functionality. Cofigured for Bugsnag.
  annotations:
    bugsnag.com/project-key: RoadieHQ/93b71ec25fd3e1d803af87d57cea2acd
spec:
  type: service
  owner: irma
  lifecycle: experimental
  system: sample-system
  providesApis:
    - test-service
