---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sonarqube-test-1
  annotations:
    github.com/project-slug: sblausten/sample-service
    sonarqube.org/project-key: sam-sample-repo
spec:
  type: service
  owner: sblausten
  lifecycle: experimental