apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bitbucket-test-service-1
  description: |
    A service for testing Bitbucket docs
  annotations:
    backstage.io/techdocs-ref: dir:./
spec:
  type: service
  owner: dtuite
  lifecycle: experimental