apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: roadie-plugins-api
  description: |
    The Plugins API endpoints for Roadie
spec:
  type: openapi
  owner: engineering
  lifecycle: production
  definition:
    $openapi: https://github.com/RoadieHQ/marketing-site/blob/main/static/plugins-openapi.json
