---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-5
  description: A test service 5
  annotations:
    github.com/project-slug: sblausten/sample-service
    backstage.io/kubernetes-label-selector: 'app=backstage,component=frontend'
    backstage.io/kubernetes-namespace: 'roadie'
    backstage.io/techdocs-ref: dir:.
    snyk.io/org-name: roadie
    snyk.io/project-ids: 63ac09c4-fd65-4f53-b9b2-c31d2dee3291
    dev.azure.com/project-repo: roadie-test/sample-service
    dev.azure.com/project: roadie-test
    dev.azure.com/build-definition: sblausten.sample-service
spec:
  type: other
  lifecycle: production
  owner: sample-team
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: test-moving-location
spec:
  type: url
  lifecycle: production
  owner: sample-team
  targets:
    - ./moving-entity2.yaml

