apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: irma-test-service
  title: Irma Test service
  description: |
    A service for testing Backstage functionality. Cofigured for Bugsnag.
  annotations:
    bugsnag.com/project-key: RoadieHQ/93b71ec25fd3e1d803af87d57cea2acd
    bugsnag.com/project-name: Test bugsnag app
    shortcut.com/project-id: '14'
    github.com/public-repository: Public
    github.com/project-slug: roadiehq/sample-service
    snyk.io/org-name: roadie
    backstage.io/techdocs-ref: dir:.
    roadie.io/techinsights-shortcut-id: "9229"
    datadog.eu/tag-name: sample-service
  labels:
    label1: test-label
    label2/label2: test-label2
spec:
  type: service
  owner: irma
  lifecycle: experimental
  system: sample-system
  providesApis:
    - test-service
