apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-techdocs-test
  description: A service for testing TechDocs.
  annotations:
    backstage.io/techdocs-ref: dir:./
spec:
  type: service
  owner: guest
  lifecycle: experimental
