apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra business unit
  annotations:
    github.com/team-slug: RoadieHQ/roadie-backstage-admin
spec:
  type: business-unit
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: [ sample-team]
  members: [sblausten]