---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf:
    - engineering
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sblausten
spec:
  memberOf:
    - engineering