apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-inline-minimal
  title: HCL Merge Inline Minimal
  description: Minimal template to verify hcl:merge runs
spec:
  owner: user:guest
  type: service

  steps:
    - id: merge
      name: Merge HCL content
      action: hcl:merge
      input:
        aSourceContent: |
          variable "region" {
            default = "us-east-1"
          }

        bSourceContent: |
          variable "region" {
            default = "eu-central-1"
          }

    - id: log
      name: Log merged HCL
      action: debug:log
      input:
        message: ${{ steps.merge.output.merged }}
