apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-inline-json
  title: HCL Merge Inline (map)
  description: Merge two map-style HCL objects
spec:
  owner: user:guest
  type: service

  steps:
    - id: merge
      name: Merge map-style HCL
      action: hcl:merge
      input:
        aSourceContent: |
          {
            "region": "us-east-1",
            "instance_type": "t2.micro"
          }

        bSourceContent: |
          {
            "region": "eu-central-1"
          }

    - id: log
      name: Log merged HCL
      action: debug:log
      input:
        message: ${{ steps.merge.output.merged }}
