apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-test
  title: HCL Merge Test
  description: Merge two map-style HCL objects
spec:
  owner: user:guest
  type: service

  steps:
    - id: merge
      name: Merge HCL content
      action: hcl:merge
      input:
        aSourceContent: |
          {
            "region": "us-east-1",
            "instance_type": "t2.micro",
            "tags": {
              "env": "dev"
            }
          }
        bSourceContent: |
          {
            "region": "eu-central-1",
            "tags": {
              "team": "engineering"
            }
          }

    - id: log
      name: Log merged result
      action: debug:log
      input:
        message: ${{ steps.merge.output.merged }}
