apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-test
  title: HCL Merge Inline Test
  description: Minimal template to verify hcl:merge runs
spec:
  owner: user:guest
  type: service

  steps:
    - id: merge
      name: Merge HCL strings
      action: hcl:merge
      input:
        aSourceContent: |
          resource "null_resource" "example" {
            provisioner "local-exec" {
              command = "echo hello"
            }
          }

        bSourceContent: |
          resource "null_resource" "example" {
            provisioner "local-exec" {
              command = "echo world"
            }
          }

    - id: log
      name: Log merged HCL
      action: debug:log
      input:
        message: ${{ steps.merge.output.merged }}
