apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-test
  title: HCL Merge Test
  description: Minimal working test for hcl:merge
spec:
  owner: user:guest
  type: service

  steps:
    - id: merge
      name: Merge HCL variables
      action: hcl:merge
      input:
        aSourceContent: |
          variable "region" {
            default = "us-east-1"
          }

          variable "instance_type" {
            default = "t2.micro"
          }

        bSourceContent: |
          variable "region" {
            default = "eu-central-1"
          }

  output:
    merged: ${{ steps.merge.output.merged }}
