apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-flat
  title: HCL Merge (flat structure)
  description: Minimal example merging two .tf files from same directory
spec:
  owner: user:guest
  type: service

  steps:
    # 1️⃣ Copy everything in the same directory into the workspace
    - id: fetch
      name: Fetch template directory
      action: fetch:template
      input:
        url: ./

    # 2️⃣ Read both .tf files
    - id: readA
      name: Read base HCL file
      action: fs:read
      input:
        path: ./base.tf

    - id: readB
      name: Read override HCL file
      action: fs:read
      input:
        path: ./override.tf

    # 3️⃣ Merge them
    - id: merge
      name: Merge HCL files
      action: hcl:merge
      input:
        aSourceContent: ${{ steps.readA.output.content }}
        bSourceContent: ${{ steps.readB.output.content }}

    # 4️⃣ Write result
    - id: write
      name: Write merged HCL
      action: fs:write
      input:
        path: ./merged.tf
        content: ${{ steps.merge.output.merged }}

  output:
    links:
      - title: View merged.tf
        url: ./merged.tf
