apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-test
  title: HCL Merge Test
  description: Minimal template to test hcl:merge action
  tags:
    - hcl
    - test
spec:
  owner: backstage/techdocs-core
  type: service
  parameters:
    - title: Basic Information
      required:
        - name
      properties:
        name:
          title: Component Name
          type: string
          description: Name of the component (lowercase, letters, numbers, and hyphens only)
          pattern: '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'
          ui:autofocus: true
          ui:help: 'Use lowercase letters, numbers, and hyphens. Must start and end with alphanumeric character.'

  steps:
    - id: test-hcl-merge
      name: Test HCL Merge
      action: hcl:merge
      input:
        aSourceContent: |
          variable "region" {
            description = "AWS region"
            type        = string
            default     = "us-west-2"
          }
        bSourceContent: |
          variable "instance_type" {
            description = "Instance type"
            type        = string
            default     = "t2.micro"
          }

    - id: test-hcl-merge-write
      name: Test HCL Merge Write
      action: hcl:merge:write
      input:
        aSourceContent: |
          variable "environment" {
            description = "Environment name"
            type        = string
            default     = "development"
          }
        bSourceContent: |
          variable "owner" {
            description = "Resource owner"
            type        = string
            default     = "devops"
          }
        outputPath: ./merged-variables.tf

    - id: create-basic-file
      name: Create basic file
      action: fetch:template
      input:
        url: ./files
        values:
          name: ${{ parameters.name }}

  output:
    links:
      - title: View merged result
        url: ./merged-variables.tf
