apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-map-inline
  title: HCL Merge Map Inline
  description: Minimal template to test hcl:merge with map-style HCL
spec:
  owner: user:guest
  type: service

  steps:
    # Merge two map-style HCL strings
    - id: merge
      name: Merge HCL maps
      action: hcl:merge
      input:
        aSourceContent: |
          {
            "region": "us-east-1",
            "instance_type": "t2.micro",
            "tags": {
              "env": "dev"
            }
          }

        bSourceContent: |
          {
            "region": "eu-central-1",
            "tags": {
              "team": "engineering"
            }
          }

    # Log the merged result
    - id: log
      name: Log merged HCL
      action: debug:log
      input:
        message: ${{ steps.merge.output.merged }}
