apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hcl-merge-test
  title: HCL Merge Test
  description: Minimal example verifying hcl:merge runs
spec:
  owner: user:guest
  type: service

  steps:
    - id: merge
      name: Merge HCL content
      action: hcl:merge
      input:
        aSourceContent: |
          variable "region" {
            default = "us-east-1"
          }

        bSourceContent: |
          variable "region" {
            default = "eu-central-1"
          }

  output:
    merged: ${{ steps.merge.output.merged }}
