apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-labels-1
  title: test-labels-1
  annotations:
    github.com/project-slug: sblausten/sample-service
  labels:
    - test1: label1
    - test2: label2
spec:
  type: service
  owner: sblausten
  lifecycle: experimental
