apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  description: Engineering team
spec:
  type: team
  profile:
    displayName: Engineering
    email: engineering@roadie.io
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: nengineering
  description: Nengineering team
spec:
  type: team
  profile:
    displayName: Nengineering
    email: nengineering@roadie.io
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  children: []
  members: [user:default/jussi, user:default/xantier]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Xantier
spec:
  profile:
    displayName: Jussi Hallila
    email: jussi@roadie.io
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [engineering, roadie-backstage-admin]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jussi
spec:
  profile:
    displayName: Jussi Hallila
    email: jussi@roadie.io
    picture: https://avatars.dicebear.com/api/avataaars/jussi-hallila.svg
  memberOf: [roadie-backstage-admin]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: roadie-backstage-admin
  description: Admins for Roadie on Roadie (roadie.roadie.so)
spec:
  type: role
  profile:
    displayName: Roadie Backstage Admin
    email: info@roadie.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: []
