---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sample-system-1
spec:
  owner: sblausten
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sample-system-2
spec:
  owner: sblausten
  partOf: system:default/sample-system-1
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: sample-system-3
spec:
  owner: sblausten
  partOf: system:default/sample-system-1
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-system-dep-1
  annotations:
    github.com/project-slug: sblausten/sample-service
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: sblausten
  consumesApi: system:default/sample-system-2
  dependsOn: system:default/sample-system-3
---