---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: append-templated-content-example
  title: Append Content example 1
  description: Example temaplate to append content
spec:
  owner: roadie
  type: service

  parameters:
    - title: PR Data
      properties:
        repository:
          title: Repository name
          type: string
          description: The name of the repository
        org:
          title: Repository Organisation
          type: string
          description: The Github org that the repository is in
        pr_branch:
          title: PR Branch
          type: string
          description: The new branch to make a pr from
    - title: Append content
      properties:
        path:
          title: Path
          type: string
          description: The path to the file you want to append this content to in the scaffolder workspace
        name:
          title: Name
          type: string
          description: The some name
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://github.com/${{ parameters.org }}/${{ parameters.repository }}
    - id: append-file
      name: Append To File Or Create New
      action: roadiehq:utils:fs:append
      input:
        path: ${{ parameters.path }}
        content: "test name: ${{ parameters.name }}
          test owner1: ${{ parameters.owner | replace(\"group:roadiehq/\", \"\") }}
          test owner2: ${{ parameters.owner | replace(\"group:.*/\", \"\") }}
          test owner3: ${{ parameters.owner | replace(\"group\", \"poop\") }}"

    - id: publish-pr
      name: Publish PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=${{ parameters.repository }}&owner=${{ parameters.org }}
        branchName:  ${{ parameters.pr_branch }}
        title: "Add test content to ${{ parameters.owner | replace(\"group:.*/\", \"\") }}"
        description: Test append or create file
    - id: log-message
      name: Log PR URL
      action: debug:log
      input:
        message: "RemoteURL: ${{ steps[\"publish-pr\"].output.remoteUrl }} owner - ${{ parameters.owner | replace(\"group:.*/\", \"\") }}"
