---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: append-file-template-1
  title: Append To File template 1
  description: Example temaplte to append to a file with on the given path with the given content in the workspace.
spec:
  owner: roadie
  type: service

  parameters:
    - title: Append To File
      properties:
        path:
          title: Path
          type: string
          description: The path to the file
        content:
          title: Content
          type: string
          description: The content to append to the file
  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://github.com/sblausten/sample-service/
        targetPath: sample-service
    - id: appendFile
      name: Append To File
      action: roadiehq:utils:fs:append
      input:
        path: sample-service/${{ parameters.path }}
        content: ${{ parameters.content }}