---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-repo-1
  title: Created Github Repo
  description: Create Github repository
spec:
  owner: sblausten
  type: infrastructure
  parameters:
    - title: Input parameters
      required:
        - owner
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            # Here's the option you can pass to the RepoUrlPicker
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow
            allowedHosts:
              - github.com
        owner:
          title: Owner
          type: string
          description: Owner of the component
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: "./template"
        values:
          owner: "${{ parameters.owner }}"
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: private
        requireCodeOwnerReviews: true
        collaborators:
          - team: engineering
            access: admin
          - team: roadie-backstage-admin
            access: pull
          - team: roadie-tech-insights-user
            access: triage
          - team: Roadie
            access: push
    - id: log-message
      name: Created Repo Log
      action: debug:log
      input:
        message: 'RemoteURL 1: ${{ steps["publish"].output.remoteUrl }}'
  output:
    links:
      - url: "${{ steps.publish.output.remoteUrl }}"
        text: The created ${{ parameters.project_name }} repository on github
