---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-shared-gha-repo
  title: Created Shared Github CI Repo
  description: Created Github repository for shared Github Actions and Reusable Workflows
  tags:
    - ci
    - github
    - gha
spec:
  owner: Ivys
  type: infrastructure
  parameters:
    - title: Input parameters
      required:
        - owner
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            # Here's the option you can pass to the RepoUrlPicker
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow
            allowedHosts:
              - github.com
        owner:
          title: Owner
          type: string
          description: Owner of the component
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: "./template"
        values:
          owner: "${{ parameters.owner }}"
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: private
        requireCodeOwnerReviews: true
        deleteBranchOnMerge: true
        allowMergeCommit: true
        allowSquashMerge: true
        allowRebaseMerge: false
        contributors:
          - team: roadiehq/engineering
            access: admin
          - team: roadiehq/roadie-backstage-admin
            access: admin
    - id: log-message
      name: Created Repo Log
      action: debug:log
      input:
        message: 'RemoteURL: ${{ steps["publish"].output.remoteUrl }}'
  output:
    links:
      - url: "${{ steps.publish.output.remoteUrl }}"
        text: The created ${{ parameters.project_name }} repository on github
