---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: enum-objects-template
  title: Enum objects
  description: Merge in some json to an existing file and open a pull request for it.
spec:
  owner: roadie
  type: service
  parameters:
    properties:
      filename:
        title: File name
        type: string
        description: The name of the file
      content:
        title: Content
        type: string
        description: The content
  steps:
    - id: create-file
      name: Create File
      action: acme:file:create
      input:
        contents: github.com?repo=${{ parameters.repository }}&owner=${{ parameters.org }}
        filename: ${{ parameters.filename }}
    - id: log-message
      name: Log PR URL
      action: debug:log
      input:
        message: 'Wrote content: ${{ steps["create-file"].output.content }}'