---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: delete-entities
  title: Deletes root entities for a given yaml file
  description: Example
spec:
  owner: roadie
  type: template
  parameters:
    - title: Entities to delete
      properties:
        catalog-info-url:
          title: Catalog info url
          type: string
          description: The full url to the yaml file you want to remove entities for from the catalog

  steps:
    - id: location
      name: Get Root Location
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/catalog/entities?filter=spec.target=${{ parameters["catalog-info-url"] }}&fields=metadata.uid,metadata.name'
    - id: log-to-delete
      action: debug:log
      input:
        message: 'Found the following location ${{ steps.location.output.body | string }} with response code ${{ steps.location.output.code }} and message ${{ steps.location.output.message }}'
    - id: parse
      name: Jsonata parse
      action: roadiehq:utils:jsonata
      input:
        data: ${{ steps.location.output.body }}
        expression: '$[0].metadata.uid'
    - id: log-to-delete
      action: debug:log
      input:
        message: 'Deleting the following root location by uuid: ${{ steps.parse.output.result }}'
    - id: delete-root
      name: Delete root
      action: http:backstage:request
      input:
        method: 'DELETE'
        path: '/catalog/entities/by-uid/${{ steps.parse.output.result }}'
    - id: refresh-catalog
      name: Refresh
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/catalog-extensions/refresh-state/garbage-collection'
    - id: log-result
      action: debug:log
      input:
        message: 'Deleted the following root location for YAML file ${{ parameters["catalog-info-url"] }} by uuid: ${{ steps.parse.output.result }}'


  output:
    path: ${{ steps.parse.output.result }}
    getResponse: '{{ steps["delete-root"].output.body }}'
    getCode: '{{ steps["delete-root"].output.code }}'
    getHeaders: '{{ steps["delete-root"].output.headers }}'