---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: http-param-new-simple
  title: Http param test simple
spec:
  owner: roadie
  type: service
  parameters:
    properties:
      - title: Custom
        properties:
#          objectFacet:
#            type: object
#            properties:
#              kind:
#                type: string
#                enum: [ 'kind', 'apiVersion' ]
#              arraySelector:
#                type: string
#                enum: [ 'facets.kind', 'facets.apiVersion' ]
          custom:
            type: string
            # Use `SelectFieldFromApi` to configure the select field for the entry.
            ui:field: SelectFieldFromApi

            ui:options:
              title: My Dropdown title
              description: My custom description for the component

              # The Path on the Backstage API and the parameters to fetch the data for the dropdown
              path: 'catalog/entity-facets'
              params:
                facet: "kind"

              # This selects the array element from the API fetch response. It finds the array with the name kind
              # under the facets object
              arraySelector: 'facets.kind'

              # (Optional) This selects the field in the array to use for the value of each select item. If its not specified
              # it will use the value of the item directly.
              valueSelector: 'count'
              # (Optional) This selects the field in the array to use for the label of each select item.
              labelSelector: 'value'
  steps:
    - id: log-result
      action: debug:log
      input:
        message: "Available Snyk projects: ${{ parameters.custom }}"