---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: http-param-new
  title: Http param test
spec:
  owner: roadie
  type: service
  parameters:
    properties:
      - title: Custom
        properties:
          facetValue:
            type: string
            enum: ['kind', 'apiVersion']
          custom:
            type: string
            # Use `SelectFieldFromApi` to configure the select field for the entry.
            ui:field: SelectFieldFromApi

            ui:options:
              title: My Dropdown title
              description: My custom description for the component

              # The Path on the Backstage API and the parameters to fetch the data for the dropdown
              path: 'catalog/entity-facets'

              # This selects the array element from the API fetch response. It finds the array with the name kind
              # under the facets object
              arraySelector: 'facets.kind'

              # (Optional) This selects the field in the array to use for the value of each select item. If its not specified
              # it will use the value of the item directly.
              valueSelector: 'count'
              # (Optional) This selects the field in the array to use for the label of each select item.
              labelSelector: 'value'

              # (Optional) This is the key of an additional dynamic query parameter that can be added to the request
              previousFieldParamRequestKey: 'facet'
              # (Optional) This is the key of a previous property who's selected value will be used as an additional query parameter value on the request
              previousFieldParamValueLookupKey: 'facetValue'
  steps:
    - id: log-result
      action: debug:log
      input:
        message: 'Available Snyk projects: ${{ parameters.custom }}'