---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: http-request-parsing
  title: Http request parsing
  description: Example template to perform a jsonata expression on input data
spec:
  owner: roadie
  type: service

  parameters:
    - id: snyk-project-id
      title: Snyk Details
      properties:
        orgName:
          title: Org
          type: string
          description: The Snyk Org name or id
        projectId:
          title: Project id
          type: string
          description: The Snyk Project Id

  steps:
    - id: get-snyk-projects
      name: Snyk Projects
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/snyk/org/${{ parameters.orgName }}/projects/${{ parameters.projectId }}'
    - id: log-result
      action: debug:log
      input:
        message: 'Available Snyk projects: ${{ steps["get-snyk-projects"].output.result }}'

  output:
    path: ${{ steps.parse.output.result }}
    getResponse: '{{ steps["get-snyk-projects"].output.body }}'
    getCode: '{{ steps["get-snyk-projects"].output.code }}'
    getHeaders: '{{ steps["get-snyk-projects"].output.headers }}'