---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: http-request-snyk
  title: Http request to snyk project
  description: Example template to perform a http request via proxy
spec:
  owner: roadie
  type: service

  parameters:
    snyk-project-id:
      title: Snyk Details
      properties:
        orgName:
          title: Org
          type: string
          description: The Snyk Org name or id
        projectId:
          title: Project id
          type: string
          description: The Snyk Project Id

  steps:
    - id: get-snyk-projects
      name: Snyk Projects
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/snyk/org/${{ parameters.snyk-project-id }}/projects'
    - id: parse
      name: Jsonata parse
      action: roadiehq:utils:jsonata
      input:
        data: ${{ steps.snyk-issues.output.body }}
        expression: '$.projects.[name, id]'
    - id: log-result
      action: debug:log
      input:
        message: 'Available Snyk projects: ${{ steps["parse"].output.result }}'

  output:
    path: ${{ steps.parse.output.result }}
    getResponse: '{{ steps["get-snyk-projects"].output.body }}'
    getCode: '{{ steps["get-snyk-projects"].output.code }}'
    getHeaders: '{{ steps["get-snyk-projects"].output.headers }}'