---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: placeholder-steps-example
spec:
  owner: sblausten
  type: example
  parameters:
    properties:
      name:
        type: string
  steps:
    - id: log-message
      action: debug:log
      input:
        message: 'Starting'
    - $yaml: 'https://github.com/sblausten/sample-service/tree/main/scaffolder/constants/step-log.yaml'