---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-params-1
  title: Test parameters 1
spec:
  owner: sblausten
  type: infrastructure
  parameters:
    - title: Fill in some steps
      required:
        - owner
      properties:
        $yaml: './library/cities.yaml'
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'The city ${{ parameters.city.name }} is at ${{ parameters.city.lat }},${{ parameters.city.lon }}'