---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: edit-file-template-example
  title: Edit file template example
  description: Example template to edit an existing file in a repo.
spec:
  owner: roadie
  type: service

  parameters:
    - title: Zip files
      properties:
        repository:
          title: Repository name
          type: string
          description: The name of the repository
        org:
          title: Repository Organisation
          type: string
          description: The Github org that the repository is in
        path:
          title: Path
          type: string
          description: The path to the file
        content:
          title: Content
          type: string
          description: The content to append to the file
        pr_branch:
          title: PR Branch
          type: string
          description: The new branch to make a pr from
  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: https://github.com/sblausten/sample-service/
    - id: zip
      name: Zip
      action: roadiehq:utils:zip
      input:
        path: ${{ parameters.path }}
        outputPath: ${{ parameters.outputPath }}

---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: serialize
  title: serialize
  description: Example template to serialize data to the YAML format
spec:
  owner: roadie
  type: service

  parameters: []
  steps:
    - id: serialize
      name: serialize
      action: roadiehq:utils:serialize:yaml
      input:
        data:
          hello: world
  output:
    path: ${{ steps.serialize.output.serialized }}