site_name: something2
repo_url: https://github.com/sblausten/sample-service
edit_uri: edit/sub-dir-documentation-2/docs/
nav:
  - First page: index.md
  - Second page: ../blob/master/docs/feature-testing.md
