site_name: mycomponent
site_description: 'My Component'

plugins:
  - monorepo

nav:
  - First page: index.md
  - Second page: other/other.md
  - Sub subdirectory docs: "!include ./sub-sub-dir-documentation/mkdocs.yml"
