site_name: sub-dir-documentation
repo_url: https://github.com/sblausten/sample-service
edit_uri: blob/main/sub-dir-documentation-2/
nav:
  - First page: index.md
  - Second page: ../blob/master/docs/feature-testing.md
