site_name: sub-dir-documentation
edit_uri: https://github.com/sblausten/sample-service/edit/main/sub-dir-documentation/
nav:
  - First page: index.md
  - Second page: ../blob/master/docs/feature-testing.md
