name: Backstage Entity Validator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - uses:  RoadieHQ/backstage-entity-validator@v0.1.0
      with:
        path: 'catalog-info.yaml'
