---
name: Record executed workflow steps in Roadie

on:
  pull_request:
    branches:
      - main

jobs:
  send_actions_to_roadie:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_ENV: test

    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Capture the actons used
        run: |
          echo "ROADIE_LIST_OF_ACTIONS=$(grep --ignore-case --no-filename -Po 'uses:\s([\w\/\@\-\.]+)' .github/workflows/* | tr '\n' ',')" >> "$GITHUB_ENV"

      - name: Capture the date
        run: |
          echo "ROADIE_DATE=$(date +"%Y-%m-%dT%H:%M:%S%z")" >> "$GITHUB_ENV"

      - name: Log github env
        run: echo "$GITHUB_ENV"

      - name: Send facts to Roadie
        id: request
        uses: tyrrrz/action-http-request@master
        with:
          url: 'https://api.roadie.so/api/tech-insights/v1/facts/9de42668-7c6a-4512-893a-b4b2f257944e'
          method: 'POST'
          headers: |
            Content-Type: application/json
            Accepts:application/json
            Authorization: bearer ${{ secrets.ROADIE_DEMO2_API_KEY}}
          body: |
            {
              "items": [{
                "timestamp": "$ROADIE_DATE",
                "entity": "component:default/sample-service",
                "facts": [{
                  "id": "6f108369-8e28-4dca-a98d-66e02e7d226a",
                  "value": "uses: ksdfjksdfk"
                }, {
                  "id": "fce91a61-d7b1-4b7f-91fa-e3a7446f1443",
                  "value": [
                    "uses: actions/checkout@v2",
                    "uses: github/codeql-action/init@v1",
                    "uses: github/codeql-action/autobuild@v1",
                    "uses: github/codeql-action/analyze@v1",
                    "uses: actions/checkout@v2",
                    "uses: actions/setup-node@v1",
                    "uses: actions/checkout@v2",
                    "uses: actions/setup-node@v2",
                    "uses: actions/setup-python@v2",
                    "uses: actions/checkout@v3"
                  ]
                }]
              }]
            }

      - name: Print outputs
        run: |
          echo "Status: ${{ steps.request.outputs.status }}"
          echo "Success: ${{ steps.request.outputs.success }}"
          echo "Headers: ${{ steps.request.outputs.headers }}"
          echo "Body: ${{ steps.request.outputs.body }}"
