---
name: Record executed workflow steps in Roadie

on:
  pull_request:
    branches:
      - main

jobs:
  send_actions_to_roadie:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_ENV: test

    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Capture the actons used
        run: |
          echo "ROADIE_LIST_OF_ACTIONS=$(grep --ignore-case --no-filename -Po 'uses:\s([\w\/\@\-\.]+)' .github/workflows/* | tr '\n' ',')" >> "$GITHUB_ENV"

      - name: Capture the date
        run: |
          echo "ROADIE_DATE=$(date +"%Y-%m-%dT%H:%M:%S%z")" >> "$GITHUB_ENV"

      - name: Log github env
        run: echo "$GITHUB_ENV"

      - name: Write json to file
        run: |
          date=$(date +"%Y-%m-%dT%H:%M:%S%z")
          string_list_of_actions=$(grep --ignore-case --no-filename -Po 'uses:\s([\w\/\@\-\.]+)' .github/workflows/*)

          cat << EOF > ./payload.json
            { "items": [{ "timestamp": "$date", "entity": "component:default/sample-service", "facts": [{ "id": "6f108369-8e28-4dca-a98d-66e02e7d226a", "value": "$string_list_of_actions" } }] }] }
          EOF

      - name: Output file
        run: cat payload.json

      - name: Send file
        run: curl -d @payload.json -H 'Content-Type:application/json' -X POST https://webhook.site/03b412f4-caa2-4ed1-9675-2163d2dda07a
