---
name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_ENV: test

    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint
